/**
 * @vitest-environment node
 */
import { describe, it, expect } from 'vitest';
import { createInstallToken, createSecureToken, isValidTokenFormat } from './token';

describe('token utility', () => {
	describe('createInstallToken', () => {
		it('generates an 8-character token', () => {
			const token = createInstallToken();
			expect(token).toHaveLength(8);
		});

		it('generates unique tokens', () => {
			const tokens = new Set<string>();
			for (let i = 0; i < 100; i++) {
				tokens.add(createInstallToken());
			}
			// All 100 tokens should be unique
			expect(tokens.size).toBe(100);
		});

		it('uses only human-friendly characters (no 0, O, 1, l, I)', () => {
			// Generate many tokens to increase chance of detecting invalid characters
			for (let i = 0; i < 100; i++) {
				const token = createInstallToken();
				expect(token).not.toMatch(/[0OlI1]/);
			}
		});

		it('generates alphanumeric tokens', () => {
			for (let i = 0; i < 100; i++) {
				const token = createInstallToken();
				expect(token).toMatch(/^[a-zA-Z0-9]+$/);
			}
		});
	});

	describe('createSecureToken', () => {
		it('generates a 21-character token by default', () => {
			const token = createSecureToken();
			expect(token).toHaveLength(21);
		});

		it('generates tokens of specified length', () => {
			expect(createSecureToken(10)).toHaveLength(10);
			expect(createSecureToken(32)).toHaveLength(32);
			expect(createSecureToken(64)).toHaveLength(64);
		});

		it('generates unique tokens', () => {
			const tokens = new Set<string>();
			for (let i = 0; i < 100; i++) {
				tokens.add(createSecureToken());
			}
			expect(tokens.size).toBe(100);
		});
	});

	describe('isValidTokenFormat', () => {
		it('returns true for valid tokens', () => {
			expect(isValidTokenFormat('abc123')).toBe(true);
			expect(isValidTokenFormat('AbC123dE')).toBe(true);
			expect(isValidTokenFormat('12345678')).toBe(true);
			expect(isValidTokenFormat('ABCDEFGH')).toBe(true);
			expect(isValidTokenFormat('abcdefghij')).toBe(true);
		});

		it('returns false for empty or null values', () => {
			expect(isValidTokenFormat('')).toBe(false);
			// @ts-expect-error - testing null input
			expect(isValidTokenFormat(null)).toBe(false);
			// @ts-expect-error - testing undefined input
			expect(isValidTokenFormat(undefined)).toBe(false);
		});

		it('returns false for non-string values', () => {
			// @ts-expect-error - testing number input
			expect(isValidTokenFormat(123456)).toBe(false);
			// @ts-expect-error - testing object input
			expect(isValidTokenFormat({})).toBe(false);
			// @ts-expect-error - testing array input
			expect(isValidTokenFormat([])).toBe(false);
		});

		it('returns false for tokens that are too short', () => {
			expect(isValidTokenFormat('abc')).toBe(false);
			expect(isValidTokenFormat('ab')).toBe(false);
			expect(isValidTokenFormat('a')).toBe(false);
			expect(isValidTokenFormat('12345')).toBe(false);
		});

		it('returns false for tokens that are too long', () => {
			expect(isValidTokenFormat('1234567890123')).toBe(false);
			expect(isValidTokenFormat('abcdefghijklmnop')).toBe(false);
		});

		it('returns false for tokens with invalid characters', () => {
			expect(isValidTokenFormat('abc-123')).toBe(false);
			expect(isValidTokenFormat('abc_123')).toBe(false);
			expect(isValidTokenFormat('abc 123')).toBe(false);
			expect(isValidTokenFormat('abc!@#')).toBe(false);
			expect(isValidTokenFormat('abc.123')).toBe(false);
		});

		it('validates tokens generated by createInstallToken', () => {
			for (let i = 0; i < 100; i++) {
				const token = createInstallToken();
				expect(isValidTokenFormat(token)).toBe(true);
			}
		});

		it('may reject tokens generated by createSecureToken due to special characters', () => {
			// createSecureToken uses nanoid's default alphabet which includes '-' and '_'
			// isValidTokenFormat only allows alphanumeric characters, so secure tokens
			// may fail validation if they contain these special characters.
			// This test verifies that behavior is consistent with the character restrictions.
			const token = 'abc-def_gh'; // Simulates a secure token with special chars
			expect(isValidTokenFormat(token)).toBe(false);
		});

		it('rejects tokens generated by createSecureToken with invalid length', () => {
			// Default length is 21, which is outside valid range
			expect(isValidTokenFormat(createSecureToken())).toBe(false);
			expect(isValidTokenFormat(createSecureToken(21))).toBe(false);
		});
	});
});
